# Generated by Django 5.1.6 on 2025-03-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lesson_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='can_preview',
            field=models.BooleanField(default=False, help_text='If user does not have access to course, can they see this?'),
        ),
    ]
