services:
  - type: web
    name: course-platform
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install --prefix src/theme/static_src
      npm run build --prefix src/theme/static_src
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn courseplatform.wsgi:application --chdir src
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: courseplatform.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: NODE_VERSION
        value: 18
