# Generated by Django 5.1.6 on 2025-03-19 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailverificationevent_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationevent',
            name='token',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
